version: '3.4'

services:
  stockdb:
    image: mongo
  
  basketdb:
    image: redis:alpine

  portainer:
    image: portainer/portainer-ce

  stock.api:
    image: ${DOCKER_REGISTRY-}stockapi
    build:
      context: .
      dockerfile: Services/Stock/Stock.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

volumes:
  mongo_data:  
  portainer_data:
